In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Escribir una función que reciba un diccionario con las alturas (en metros) de los integrantes del grupo y devuelva una serie con la altura mínima, la máxima, media y la desviación estándar.

In [ ]:
d=dict()

for i in range(4):
    x= float(input("dame tu altura: "))
    y= input("Dame tu nombre: ")
    d[y] = x

print(d)
print()
tabla= pd.Series(d)
print(tabla)
print()
print(tabla.max())
print()
print(tabla.min())
print()
print(tabla.std())
print()
print(tabla.sum() /4)

<font color='green'>Fin Actividad</font>

Escribir una función que reciba un diccionario con las alturas (en metros) de los integrantes del grupo y devuelva una serie con las alturas mayores a 1.75 ordenadas de mayor a menor.

In [107]:
personas = {
    "Juan": 175,
    "María": 160,
    "Pedro": 180 ,
    "Ana": 190
}

serie=pd.Series(personas)
cumplen={}

for llave,valor in sorted(list(personas.items())):
    if valor > 175:
        cumplen[llave]=valor
        
pd.Series(cumplen)

Ana      190
Pedro    180
dtype: int64

<font color='green'>Fin Actividad</font>

Dada la siguiente serie:

```
s2 = pd.Series([1, 2, 3, 4, 5], index=['a-1', 'b-2', 'c-3', 'a-4', 'b-5'])
```
Selecciona aquellos valores cuyos índices comienzan con 'a-'.

In [108]:
s2 = pd.Series([1, 2, 3, 4, 5], index=['a-1', 'b-2', 'c-3', 'a-4', 'b-5'])


for i in s2.index:
    if "a-" in i:
        print(s2.loc[i])

1
4

<font color='green'>Fin Actividad</font>

Dada la siguiente serie:

```
s3 = pd.Series(list(range(20)), index=list(range(20, 0, -1)))
```
Selecciona aquellos valores que sean pares y cuyos índices sean impares.

In [109]:
s3 = pd.Series(list(range(20)), index=list(range(21, 1, -1)))

valor=[]
inde=[]

for i in s3:
    if i%2 ==0:
        valor.append(i)
        
for i in s3.index:
    if i%2 !=0:
        inde.append(i)
        
s3_c= pd.Series(valor,inde)

print(s3_c)

21     0
19     2
17     4
15     6
13     8
11    10
9     12
7     14
5     16
3     18
dtype: int64

<font color='green'>Fin Actividad</font>

Dada la siguiente serie:

```
s4 = pd.Series(list(range(10, 101, 10)))
```
Utilizando una función, selecciona aquellos números que son divisibles por 3.

In [110]:
s4 = pd.Series(list(range(10, 101, 10)))

def divisible(n):
    if n%3 ==0:
        print(f"{n} Es div por 3")
    else:
        print(f"{n} No es div por 3")

for i in s4:
    divisible(i)

10 No es div por 3
20 No es div por 3
30 Es div por 3
40 No es div por 3
50 No es div por 3
60 Es div por 3
70 No es div por 3
80 No es div por 3
90 Es div por 3
100 No es div por 3

<font color='green'>Fin Actividad</font>

Dada la siguiente serie:

```
s5 = pd.Series([10, 23, 30, 33, 45, 52, 68, 77, 81, 97])
```
Selecciona todos los valores que sean primos o múltiplos de 7. Posteriormente, reasigna esos valores seleccionados al cuadrado de su valor original.

In [111]:
s5 = pd.Series([10, 23, 30, 33, 45, 52, 68, 77, 81, 97])
lista=[]
lista_elevado=[]

for i in s5:
    for j in range(2,i):
        if i % j == 0 and i not in lista:
            lista.append(i)

    for n in range(i):
        if i % 7 == 0:
            if i not in lista:
                lista.append(i)

for k in lista:
    x= k**2
    lista_elevado.append(x)

print(pd.Series(lista_elevado, index=lista))

10     100
30     900
33    1089
45    2025
52    2704
68    4624
77    5929
81    6561
dtype: int64

<font color='green'>Fin Actividad</font>

Imagina que estás trabajando con una serie de datos financieros, donde cada índice representa una fecha específica y cada valor representa el precio de cierre de una acción en esa fecha. Las fechas no están en orden y algunas de ellas son particularmente importantes para ti debido a eventos externos.

En esta actividad deberás seleccionar precios de cierre en fechas específicas, y para ello deberás combinar el uso de loc, iloc y expresiones.

```
dates = [datetime.date(2023, 5, 15), datetime.date(2023, 1, 10), datetime.date(2023, 3, 23),
         datetime.date(2023, 2, 15), datetime.date(2023, 8, 30), datetime.date(2023, 4, 5)]

prices = [120.5, 115.2, 112.8, 116.5, 127.4, 119.0]

data = pd.Series(prices, index=dates)
```

1. Ordena la serie según sus índices de fecha.
2. Utiliza iloc para seleccionar el precio de cierre de la segunda fecha más reciente en la serie ordenada.
3. Iimagina que sabes que hubo un evento importante el 15 de febrero de 2023 y quieres saber cómo afectó el precio posteriormente. Utiliza loc para seleccionar todos los precios desde esa fecha en adelante.
4. Utilizando una combinación de expresiones, selecciona los precios que estén por encima del precio medio pero solo para fechas anteriores al 1 de abril de 2023.

In [112]:
import datetime 

dates = [datetime.date(2023, 5, 15), datetime.date(2023, 1, 10), datetime.date(2023, 3, 23),
         datetime.date(2023, 2, 15), datetime.date(2023, 8, 30), datetime.date(2023, 4, 5)]

prices = [120.5, 115.2, 112.8, 116.5, 127.4, 119.0]

data=pd.Series(prices, index=dates)


fechas_or= data.sort_index()

c=0
for i in prices:
    c+=i

precio_medio=round(c/6 , 1)

lista=[]
for fecha,precio in fechas_or.items():
    if precio>precio_medio and fecha<datetime.date(2023, 4, 1):
        lista.append(fecha,precio_medio)

print(fechas_or)
print()
print(fechas_or.iloc[4])
print()
print(fechas_or.loc[datetime.date(2023,2,15) : datetime.date(2023,8,30)])
print()
print(pd.Series(lista))

2023-01-10    115.2
2023-02-15    116.5
2023-03-23    112.8
2023-04-05    119.0
2023-05-15    120.5
2023-08-30    127.4
dtype: float64

120.5

2023-02-15    116.5
2023-03-23    112.8
2023-04-05    119.0
2023-05-15    120.5
2023-08-30    127.4
dtype: float64

Series([], dtype: object)

<font color='green'>Fin Actividad</font>

### <font color='green'>Actividad 2</font>

Dado el siguiente DataFrame:

```
dates = pd.date_range('20230101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
```

Selecciona las filas correspondientes a las fechas después del 2023-01-03.

In [5]:
dates = pd.date_range('20230101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

df1[2:]

                   A         B         C         D
2023-01-03 -0.073723  0.287153 -0.325867 -0.874415
2023-01-04  0.068285 -1.492964  0.268935  1.145671
2023-01-05 -0.674546 -0.033967 -0.012685  0.280403
2023-01-06 -1.306799 -1.739995 -0.777812  0.920395

### <font color='green'>Actividad 3</font>

Dado el siguiente DataFrame:

```
df2 = pd.DataFrame(np.random.randint(0, 100, size=(8, 4)), columns=list('WXYZ'))
```

Selecciona las filas de índice 2 a 5, pero solo las columnas 'W' y 'Z'.

In [13]:
df2 = pd.DataFrame(np.random.randint(0, 100, size=(8, 4)), columns=list('WXYZ'))

df2.loc[2:5,["W","Z"]]

    W   Z
2  99  93
3  16  96
4  41  52
5  75  83

### <font color='green'>Actividad 4</font>

Dado el siguiente DataFrame:

```
data = {
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': np.random.randint(1, 10, 8),
    'D': np.random.randint(1, 10, 8)
}
df3 = pd.DataFrame(data)
```

Selecciona todos los registros donde A sea 'foo' y B no sea 'three'.

In [42]:
data = {
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': np.random.randint(1, 10, 8),
    'D': np.random.randint(1, 10, 8)
}
df3 = pd.DataFrame(data)

df3a=df3[(df3['A']=="foo") & ((df3['B']=="one") | (df3['B']=="two"))]
df3a

     A    B  C  D
0  foo  one  9  8
2  foo  two  3  4
4  foo  two  8  4
6  foo  one  7  2

### <font color='green'>Actividad 5</font>

Dado el siguiente DataFrame:

```
df4 = pd.DataFrame(np.random.randint(-10, 10, size=(6, 6)), columns=list('ABCDEF'))
```

Crea una máscara que identifique los valores negativos en el DataFrame y luego reemplace esos valores con su valor absoluto utilizando una función.

In [72]:
df4 = pd.DataFrame(np.random.randint(-10, 10, size=(6, 6)), columns=list('ABCDEF'))

df_nega=df4[df4<0].stack().reset_index(drop=True) 
#.stack(): Colapsa el DataFrame en una serie eliminando los NaN, por lo que solo te quedas con los valores negativos.
#.reset_index(drop=True): Restablece los índices del nuevo DataFrame y elimina los índices antiguos.

def valor_absoluto(df):
    return df.abs() #Función que aplica el valor absoluto a todos los elementos de un DataFrame/ df.abs() 

print(valor_absoluto(df_nega))

0      1.0
1      8.0
2      9.0
3      2.0
4      2.0
5     10.0
6      9.0
7      5.0
8      8.0
9      9.0
10     2.0
11     2.0
12     1.0
13     9.0
14     3.0
15    10.0
16     7.0
17    10.0
18     3.0
dtype: float64

### <font color='green'>Actividad 6</font>

Dado el siguiente DataFrame:

```
df5 = pd.DataFrame({
    'key': list('ABCDAE'),
    'values': [10, 15, 20, 25, 30, 35],
    'dates': pd.date_range(start='20230101', periods=6)
})
```

Selecciona las filas con key igual a 'A', pero solo muestra las dos primeras entradas y las columnas a partir de la segunda columna.

In [85]:
df5 = pd.DataFrame({
    'key': list('ABCDAE'),
    'values': [10, 15, 20, 25, 30, 35],
    'dates': pd.date_range(start='20230101', periods=6)
})

df5a=df5.set_index("key")
df5a.index=="A"
df5b=df5a.loc["A"]
df5b

     values      dates
key
A        10 2023-01-01
A        30 2023-01-05

### <font color='green'>Actividad 7</font>

Dado el siguiente DataFrame:

```
df6 = pd.DataFrame({
    'region': ['North', 'South', 'West', 'East', 'Central', 'North'],
    'sales': [320, 234, 489, 278, 213, 389],
    'expenses': [245, 267, 248, 310, 190, 245]
})
```

Identifica y selecciona las regiones donde las ventas exceden los gastos por más del 20%.

In [104]:
df6 = pd.DataFrame({
    'region': ['North', 'South', 'West', 'East', 'Central', 'North'],
    'sales': [320, 234, 489, 278, 213, 389],
    'expenses': [245, 267, 248, 310, 190, 245]
})
df6a=df6.set_index("region")
df6b=df6a[df6a["sales"]>df6a["expenses"]*1.20]

df6b

        sales  expenses
region
North     320       245
West      489       248
North     389       245



### <font color='green'>Actividad 8</font>

Estás analizando un conjunto de datos de ventas y existencias de una tienda a lo largo del tiempo. Tienes una Serie que representa las fechas en que se realizaron auditorías sorpresa y un DataFrame que contiene registros de ventas diarias, existencias y otros detalles relevantes.

El objetivo es inspeccionar cómo se comportaron las ventas y existencias en las fechas cercanas a las auditorías.


```
# Serie de auditorías
audit_dates = pd.Series(pd.to_datetime(['2023-01-15', '2023-03-05', '2023-06-20', '2023-08-25']))

# DataFrame de registros
dates = pd.date_range('20230101', '20230930', freq='D')
data = {
    'sales': np.random.randint(50, 200, len(dates)),
    'stock': np.random.randint(100, 500, len(dates)),
    'returns': np.random.randint(1, 50, len(dates))
}
df = pd.DataFrame(data, index=dates)
```

1. Identifica las fechas en las que se realizaron las auditorías utilizando el método isin() en el DataFrame, y muestra las ventas y existencias para esas fechas.
2. Usando iloc, selecciona los registros de 2 días antes y 2 días después de cada fecha de auditoría (es decir, una ventana de 5 días para cada auditoría).
3. Filtra este resultado para mostrar sólo aquellos días en los que las ventas fueron menores que el promedio de ventas del período y las existencias estaban por encima del promedio.
4. Utiliza el método loc para agregar una nueva columna llamada "audit_period" al DataFrame original, marcando con True los registros que caen dentro de las ventanas de auditoría y False en caso contrario.

In [ ]:
# Serie de auditorías
audit_dates = pd.Series(pd.to_datetime(['2023-01-15', '2023-03-05', '2023-06-20', '2023-08-25']))

# DataFrame de registros
dates = pd.date_range('20230101', '20230930', freq='D')
data = {
    'sales': np.random.randint(50, 200, len(dates)),
    'stock': np.random.randint(100, 500, len(dates)),
    'returns': np.random.randint(1, 50, len(dates))
}
df = pd.DataFrame(data, index=dates)

display(df)
print()
df[df.index.isin(audit_dates)]

l_resultado=[]
for i in audit_dates:
    if i in df.index:
        print(df.iloc[df.index.get_loc(i)-2:df.index.get_loc(i)+3])
        l_resultado.append(df.iloc[df.index.get_loc(i)-2:df.index.get_loc(i)+3]) #lo guardamos en la lista dado que si no hacemos esto el resultado solo se guarda en la ultima iteracion

resultado=pd.concat(l_resultado) #concatenamos los resultados

print(resultado)
promedio_v=resultado["sales"].mean()
promedio_s=resultado["stock"].mean()
display(resultado[resultado["sales"]<promedio_v] , resultado[resultado["stock"]>promedio_s])

df["audit_period"]=df.index.isin(['2023-01-15', '2023-03-05', '2023-06-20', '2023-08-25'])
display(df)

### <font color='green'>Actividad 2</font>

Dado un DataFrame con registros de ventas y retornos de productos, debes calcular la tasa de retorno y almacenarla en una Serie.

```
dates = pd.date_range('20230101', periods=10)
df1 = pd.DataFrame({
    'sales': np.random.randint(50, 200, len(dates)),
    'returns': np.random.randint(1, 20, len(dates))
}, index=dates)
```

1. Calcula la tasa de retorno como returns / sales.
2. Almacena el resultado en una Serie con el mismo índice de fechas.
3. Une esta Serie al DataFrame original como una nueva columna llamada 'return_rate'.

In [13]:
dates = pd.date_range('20230101', periods=10)
df1 = pd.DataFrame({
    'sales': np.random.randint(50, 200, len(dates)),
    'returns': np.random.randint(1, 20, len(dates))
}, index=dates)

serie=df1["returns"]/df1["sales"]
df1["return_rate"]=serie
df1

            sales  returns  return_rate
2023-01-01     52       13     0.250000
2023-01-02     82       19     0.231707
2023-01-03     83       11     0.132530
2023-01-04    178        2     0.011236
2023-01-05    168       18     0.107143
2023-01-06    148        9     0.060811
2023-01-07     63       12     0.190476
2023-01-08     90        8     0.088889
2023-01-09     80        8     0.100000
2023-01-10     74       12     0.162162

### <font color='green'>Actividad 3</font>

Tienes un DataFrame de precios de acciones y una Serie que representa el volumen de acciones negociadas. Algunos días, el volumen es desconocido y aparece como NaN en la Serie. Tu objetivo es llenar estos valores, pero no con un método simple.

```
dates = pd.date_range('20230101', periods=8)
df2 = pd.DataFrame({
    'price': np.random.randn(len(dates)).cumsum() + 50
}, index=dates)

volume = pd.Series(np.where(np.random.choice([True, False], len(dates)), np.random.randint(1000, 5000, len(dates)), np.nan), index=dates)
```

1. En los días con volumen faltante, llena el valor con el volumen del día anterior si el precio de la acción ha aumentado, o con el volumen del día siguiente si el precio ha disminuido.
2. Añade la Serie de volumen al DataFrame como una nueva columna.

In [62]:
dates = pd.date_range('20230101', periods=8)
df2 = pd.DataFrame({
    'price': np.random.randn(len(dates)).cumsum() + 50
}, index=dates)

volume = pd.Series(np.where(np.random.choice([True, False], len(dates)), np.random.randint(1000, 5000, len(dates)), np.nan), index=dates)

df2["dif"]=df2["price"].diff()
df2["dif"].iloc[0]=0
nulo= volume.isnull()

while not nulo.all(): # Mientras no todos los valores en 'nulo' sean True
    if (df2["dif"]>0).any():
        volume= volume.ffill()
    else:
        volume= volume.bfill()
    break

nulo2= volume.isnull()
if nulo2.any()==True:
    volume= volume.fillna(0)

df2["volume"]=volume

display(df2)

C:\Users\renat\AppData\Local\Temp\ipykernel_14456\89399131.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2["dif"].iloc[0]=0

                price       dif  volume
2023-01-01  50.094890  0.000000  1652.0
2023-01-02  49.902816 -0.192074  1652.0
2023-01-03  50.383009  0.480193  2538.0
2023-01-04  49.096257 -1.286752  2948.0
2023-01-05  50.461904  1.365647  1223.0
2023-01-06  52.248173  1.786270  1223.0
2023-01-07  50.972070 -1.276103  2048.0
2023-01-08  52.699477  1.727407  1399.0

### <font color='green'>Actividad 4</font>

Tienes un DataFrame con información de ventas y gastos por departamento. Se te pide extraer ciertos departamentos y realizar una transformación en los datos.

```
departments = ["HR", "Sales", "Tech", "Admin", "Finance"]
df3 = pd.DataFrame({
    'sales': np.random.randint(10, 100, len(departments)),
    'expenses': np.random.randint(10, 50, len(departments))
}, index=departments)
```

1. Extrae sólo los departamentos "Sales" y "Tech".
2. Crea una Serie que represente el margen de beneficio (definido como sales - expenses).
3. Combina esta Serie con el subconjunto del DataFrame original utilizando pd.concat.

In [7]:
departments = ["HR", "Sales", "Tech", "Admin", "Finance"]
df3 = pd.DataFrame({
    'sales': np.random.randint(10, 100, len(departments)),
    'expenses': np.random.randint(10, 50, len(departments))
}, index=departments)

sales=df3["sales"]
tech=df3.loc["Tech"]

beneficio= df3["sales"]-df3["expenses"]

pd.concat([df3, beneficio],axis=1)

         sales  expenses   0
HR          97        37  60
Sales       91        32  59
Tech        47        23  24
Admin       38        37   1
Finance     54        21  33

### <font color='green'>Actividad 5</font>

Estás trabajando con un DataFrame que contiene ventas trimestrales y anuales de diferentes años. Tu objetivo es calcular el promedio de ventas trimestrales para cada año y agregarlo como una nueva entrada en la Serie.

```
years = [2021, 2022, 2023]
entries = ["Q1", "Q2", "Q3", "Q4", "Annual"]
index = pd.MultiIndex.from_product([years, entries], names=["Year", "Entry"])
df4 = pd.DataFrame({
    'sales': np.random.randint(500, 1500, len(index))
}, index=index)
```

1. Calcula el promedio de ventas trimestrales para cada año (no consideres la entrada "Annual").
2. Añade esta información como una nueva entrada llamada "Quarterly_avg" en el DataFrame original.

In [22]:
years = [2021, 2022, 2023]
entries = ["Q1", "Q2", "Q3", "Q4", "Annual"]
index = pd.MultiIndex.from_product([years, entries], names=["Year", "Entry"])
df4 = pd.DataFrame({
    'sales': np.random.randint(500, 1500, len(index))
}, index=index)

df_f=df4[df4.index.get_level_values("Entry")!="Annual"] #tomamos las entradas distintas de annual
promedio=df_f["sales"].mean() #promedio

df_reset=df4.reset_index() #reseteamos los indices
fila= pd.DataFrame({"Year": ["Promedio"], "Entry": ["Promedio"], "sales": [promedio]}) #nueva fila
df_reset= pd.concat([df_reset, fila], ignore_index=True) #las unimos
df_final = df_reset.set_index(['Year', 'Entry']) #reseteamos

df_final

                         sales
Year     Entry
2021     Q1         723.000000
         Q2         752.000000
         Q3         679.000000
         Q4        1405.000000
         Annual     904.000000
2022     Q1        1346.000000
         Q2         579.000000
         Q3        1257.000000
         Q4        1202.000000
         Annual    1282.000000
2023     Q1         663.000000
         Q2         809.000000
         Q3        1377.000000
         Q4         690.000000
         Annual     672.000000
Promedio Promedio   956.833333

## <font color='green'>Actividad 1</font>

En el siguiente dataframe se guardan los datos personales de un grupo de clientes:

```
clientes = {'nombre' : ['Orlando' ,'Inés' ,'Michelle', 'Alberto', 'Esteban'],
           'apellido' : ['Figueroa' ,'Benítez' ,'Gómez', 'Riesco', 'Martínez'],
           'edad' : [30 ,21 ,29 ,22, 24]}
clientes = pd.DataFrame(clientes, columns = ['nombre', 'apellido', 'edad'])
```
En el siguiente se incluyen las transacciones:



```
facturas = {'factura_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            'cliente_id' : [3, 2, 7, 2, 7, 3, 1, 4 ,2, 3, 6, 2],
            'cantidad': [77.91, 24.36, 74.65, 19.75, 27.46, 17.13, 45.77, 81.7, 14.41, 52.69, 32.03, 12.78]}
facturas = pd.DataFrame(facturas, columns = ['factura_id', 'cliente_id', 'cantidad'])
```

Considere el dataframe llamado nuevos_clientes:



```
nuevos_clientes = pd.DataFrame({'nombre' : ['Rebeca'],
                            'apellido' : ['Rojas'],
                            'edad' : [21]},
                           columns = ['nombre', 'apellido', 'edad'])
```

1. Agregar los nuevos clientes al dataframe *clientes*.
2. Actualice los valores para los índices del dataframe *clientes*.
3. Genere un dataframe llamado *cliente_id* y agréguelo como una columna nueva a *clientes*.
4. Realice la unión de los dataframes *clientes* y *facturas* de manera que el resultado sean todos los registros almacenados.
5. Agregue al dataframe *nuevos clientes* a todos los integrantes del grupo, repita el proceso y haga el join entre clientes y facturas pero su resultado debe contener solo las filas con etiquetas comunes.

In [35]:
clientes = {'nombre' : ['Orlando' ,'Inés' ,'Michelle', 'Alberto', 'Esteban'],
           'apellido' : ['Figueroa' ,'Benítez' ,'Gómez', 'Riesco', 'Martínez'],
           'edad' : [30 ,21 ,29 ,22, 24]}
clientes = pd.DataFrame(clientes, columns = ['nombre', 'apellido', 'edad'])

facturas = {'factura_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            'cliente_id' : [3, 2, 7, 2, 7, 3, 1, 4 ,2, 3, 6, 2],
            'cantidad': [77.91, 24.36, 74.65, 19.75, 27.46, 17.13, 45.77, 81.7, 14.41, 52.69, 32.03, 12.78]}
facturas = pd.DataFrame(facturas, columns = ['factura_id', 'cliente_id', 'cantidad'])

nuevos_clientes = pd.DataFrame({'nombre' : ['Rebeca'],
                            'apellido' : ['Rojas'],
                            'edad' : [21]},
                           columns = ['nombre', 'apellido', 'edad'])

df= pd.concat([clientes, nuevos_clientes],ignore_index=True)
df= pd.concat([clientes, facturas], axis=1)
df=df.dropna()
df=df.set_index("cliente_id")
df

              nombre  apellido  edad  factura_id  cantidad
cliente_id
3            Orlando  Figueroa  30.0           1     77.91
2               Inés   Benítez  21.0           2     24.36
7           Michelle     Gómez  29.0           3     74.65
2            Alberto    Riesco  22.0           4     19.75
7            Esteban  Martínez  24.0           5     27.46

### <font color='green'>Actividad 3</font>

Una empresa con múltiples tiendas registra las ventas diarias en DataFrames separados. Los registros de algunas tiendas se han retrasado, y tu objetivo es combinar estos registros de ventas y llenar los datos faltantes de las tiendas retrasadas.

```
dates = pd.date_range('20230101', '20230110')

# Ventas de la tienda A
sales_A = pd.DataFrame({
    'date': dates,
    'sales_A': np.random.randint(50, 200, len(dates))
})

# Ventas de la tienda B (notar que faltan algunos días)
sales_B = pd.DataFrame({
    'date': dates[[0,1,2,5,6,7,9]],
    'sales_B': np.random.randint(50, 200, 7)
})
```

1. Fusiona los DataFrames sales_A y sales_B usando la columna date como clave. Asegúrate de que todos los días estén presentes en el DataFrame resultante.
2. Rellena los valores faltantes de sales_B utilizando una estrategia que consideres adecuada (p.ej., media, mediana, interpolación, etc.).
3. Crea una columna adicional en el DataFrame fusionado que represente la venta total diaria (suma de ambas tiendas).

In [7]:
dates = pd.date_range('20230101', '20230110')

# Ventas de la tienda A
sales_A = pd.DataFrame({
    'date': dates,
    'sales_A': np.random.randint(50, 200, len(dates))
})

# Ventas de la tienda B (notar que faltan algunos días)
sales_B = pd.DataFrame({
    'date': dates[[0,1,2,5,6,7,9]],
    'sales_B': np.random.randint(50, 200, 7)
})

df=pd.merge(sales_A, sales_B, how="outer")
boleano= df.isna() #Genera una máscara booleana para los valores NaN

df[boleano]= df["sales_B"].mean() #Rellenar los valores NaN
df["suma"]= df["sales_A"]+df["sales_B"]

df

        date  sales_A     sales_B        suma
0 2023-01-01      167  125.000000  292.000000
1 2023-01-02       73  121.000000  194.000000
2 2023-01-03      136  131.000000  267.000000
3 2023-01-04       50  145.142857  195.142857
4 2023-01-05      165  145.142857  310.142857
5 2023-01-06      138  106.000000  244.000000
6 2023-01-07      133  185.000000  318.000000
7 2023-01-08       88  158.000000  246.000000
8 2023-01-09      177  145.142857  322.142857
9 2023-01-10      187  190.000000  377.000000

### <font color='green'>Actividad 4</font>

Tienes tres DataFrames: df1, df2 y df3. Cada DataFrame tiene una columna 'ID', una columna 'Valor' y una columna 'Categoría'.

```
# df1, df2 y df3
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 6, 7, 10],
    'Valor': [100, 200, 300, 350, 400, 450],
    'Categoria': ['A', 'B', 'A', 'C', 'B', 'A']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4, 6, 8, 9],
    'Valor': [220, 330, 440, 355, 465, 575],
    'Categoria': ['B', 'A', 'C', 'C', 'A', 'B']
})

df3 = pd.DataFrame({
    'ID': [3, 4, 5, 7, 8, 10],
    'Valor': [350, 470, 590, 410, 480, 460],
    'Estado': ['Activo', 'Inactivo', 'Activo', 'Activo', 'Inactivo', 'Activo']
})
```

Si un 'ID' está presente en más de un DataFrame, deseas unir sus valores en función de la siguiente lógica:
* Si un ID está en df1 y df2 (pero no en df3), toma el promedio de 'Valor'.

* Si un ID está en df1 y df3 (pero no en df2), suma los 'Valores'.

* Si un ID está en df2 y df3 (pero no en df1), resta el 'Valor' en df3 del 'Valor' en df2.

* Si un ID está en los tres DataFrames, multiplica los tres 'Valores' juntos.

Además, si el ID coincide entre df1 y df2, combine la 'Categoria' de ambos DataFrames en una nueva columna, y si el ID coincide entre df1 y df3, añada la columna 'Estado' de df3 al DataFrame resultante.

In [23]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 6, 7, 10],
    'Valor': [100, 200, 300, 350, 400, 450],
    'Categoria': ['A', 'B', 'A', 'C', 'B', 'A']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4, 6, 8, 9],
    'Valor': [220, 330, 440, 355, 465, 575],
    'Categoria': ['B', 'A', 'C', 'C', 'A', 'B']
})

df3 = pd.DataFrame({
    'ID': [3, 4, 5, 7, 8, 10],
    'Valor': [350, 470, 590, 410, 480, 460],
    'Estado': ['Activo', 'Inactivo', 'Activo', 'Activo', 'Inactivo', 'Activo']
})

ids1_2= pd.merge(df1,df2, on="ID", suffixes=("_df1", "_df2")) #los juntamos y le damos los sufijos para que no sean x e y
comp= ids1_2[~ids1_2["ID"].isin(df3)] #vemos los valores que no estan en df3

comp["media"]=comp[["Valor_df1","Valor_df2"]].mean(axis=1) #calculamos la media


#el ejercicio es lo mismo pero con el resto

display(df1)
display(df2)
display(df3)
display(comp[["ID","media"]])
display()

   ID  Valor Categoria
0   1    100         A
1   2    200         B
2   3    300         A
3   6    350         C
4   7    400         B
5  10    450         A

   ID  Valor Categoria
0   2    220         B
1   3    330         A
2   4    440         C
3   6    355         C
4   8    465         A
5   9    575         B

   ID  Valor    Estado
0   3    350    Activo
1   4    470  Inactivo
2   5    590    Activo
3   7    410    Activo
4   8    480  Inactivo
5  10    460    Activo

   ID  media
0   2  210.0
1   3  315.0
2   6  352.5

### <font color='green'>Actividad 5</font>

Dado un DataFrame df_main con un MultiIndex (dos niveles: 'Key1' y 'Key2') y un df_ref con el mismo MultiIndex:

```
arrays = [
    ['A', 'A', 'B', 'B', 'C', 'C'],
    [1, 2, 1, 2, 1, 2]
]

index_main = pd.MultiIndex.from_arrays(arrays, names=('Key1', 'Key2'))

df_main = pd.DataFrame({
    'Valor': [10, 20, 30, 40, 50, 60],
    'Descripción': ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot']
}, index=index_main)

index_ref = pd.MultiIndex.from_arrays([
    ['A', 'B', 'B', 'C', 'C', 'D', 'D'],
    [1, 1, 2, 1, 2, 1, 2]
], names=('Key1', 'Key2'))

df_ref = pd.DataFrame({
    'Referencia': [100, 200, 300, 400, 500, 600, 700],
    'Comentario': ['Uno', 'Dos', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'Siete']
}, index=index_ref)
```

1. Fusiona estos DataFrames en uno solo.

2. En lugar de una fusión estándar, para aquellos niveles de MultiIndex donde los valores no coinciden entre df_main y df_ref, llenar esos valores con el valor anterior o posterior más cercano.

3. Añade una nueva columna que combine las columnas 'Descripción' y 'Comentario' para las claves que coinciden.

In [34]:
arrays = [
    ['A', 'A', 'B', 'B', 'C', 'C'],
    [1, 2, 1, 2, 1, 2]
]

index_main = pd.MultiIndex.from_arrays(arrays, names=('Key1', 'Key2'))

df_main = pd.DataFrame({
    'Valor': [10, 20, 30, 40, 50, 60],
    'Descripción': ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot']
}, index=index_main)

index_ref = pd.MultiIndex.from_arrays([
    ['A', 'B', 'B', 'C', 'C', 'D', 'D'],
    [1, 1, 2, 1, 2, 1, 2]
], names=('Key1', 'Key2'))

df_ref = pd.DataFrame({
    'Referencia': [100, 200, 300, 400, 500, 600, 700],
    'Comentario': ['Uno', 'Dos', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'Siete']
}, index=index_ref)

df= pd.concat([df_main, df_ref], axis=1)

boole= df.isna()
if boole.any().any(): #el primero verifica columna a columna si hay al mnenos un true: el segundo verifica si alguna columna tiene true 
    df=df.ffill()

display(df_main)
display(index_ref)
display(df_ref)
display(df)

           Valor Descripción
Key1 Key2
A    1        10       Alpha
     2        20       Bravo
B    1        30     Charlie
     2        40       Delta
C    1        50        Echo
     2        60     Foxtrot

MultiIndex([('A', 1),
            ('B', 1),
            ('B', 2),
            ('C', 1),
            ('C', 2),
            ('D', 1),
            ('D', 2)],
           names=['Key1', 'Key2'])

           Referencia Comentario
Key1 Key2
A    1            100        Uno
B    1            200        Dos
     2            300       Tres
C    1            400     Cuatro
     2            500      Cinco
D    1            600       Seis
     2            700      Siete

           Valor Descripción  Referencia Comentario
Key1 Key2
A    1      10.0       Alpha       100.0        Uno
     2      20.0       Bravo       100.0        Uno
B    1      30.0     Charlie       200.0        Dos
     2      40.0       Delta       300.0       Tres
C    1      50.0        Echo       400.0     Cuatro
     2      60.0     Foxtrot       500.0      Cinco
D    1      60.0     Foxtrot       600.0       Seis
     2      60.0     Foxtrot       700.0      Siete

          Descripción Comentario
Key1 Key2
A    1          Alpha        Uno
     2          Bravo        NaN
B    1        Charlie        Dos
     2          Delta       Tres
C    1           Echo     Cuatro
     2        Foxtrot      Cinco
D    1            NaN       Seis
     2            NaN      Siete

### <font color='green'>Actividad 1</font>

Se tiene una serie temporal de ventas mensuales a lo largo de un año. Sin embargo, algunos meses faltan en el índice. Tu tarea es reindexar la serie para incluir todos los meses del año y tratar los valores faltantes.

```
months = ['Enero', 'Febrero', 'Marzo', 'Junio', 'Agosto', 'Noviembre', 'Diciembre']
sales = pd.Series([200, 220, 210, 230, 240, 250, 260], index=months)
```

1. Reindexa la serie sales para incluir todos los meses del año.
2. Rellena los valores faltantes con 0.
3. Calcula la media de ventas y reemplaza los valores faltantes con este valor en lugar de 0.

In [ ]:
months = ['Enero', 'Febrero', 'Marzo', 'Junio', 'Agosto', 'Noviembre', 'Diciembre']
sales = pd.Series([200, 220, 210, 230, 240, 250, 260], index=months)

meses= sales.reindex(['Enero', 'Febrero', 'Marzo',"Abril","Mayo", 'Junio',"Julio", 'Agosto',"Septiembre","Octubre", 'Noviembre', 'Diciembre'])
#meses= meses.fillna(0) o tambien podemos añadir el fill_value en el reindex
media= meses.mean()
meses= sales.reindex(['Enero', 'Febrero', 'Marzo',"Abril","Mayo", 'Junio',"Julio", 'Agosto',"Septiembre","Octubre", 'Noviembre', 'Diciembre'], fill_value=media) #asi
display(meses)

Enero         200.0
Febrero       220.0
Marzo         210.0
Abril         230.0
Mayo          230.0
Junio         230.0
Julio         230.0
Agosto        240.0
Septiembre    230.0
Octubre       230.0
Noviembre     250.0
Diciembre     260.0
dtype: float64

### <font color='green'>Actividad 2</font>

Supongamos que tienes dos DataFrames: uno con las ventas del primer semestre y otro con las ventas del segundo semestre. Quieres combinarlos en un solo DataFrame que contenga las ventas anuales, pero algunos productos están presentes en uno de los DataFrames y no en el otro.

```
products_first_semester = ['A', 'B', 'C', 'D']
sales_first_semester = pd.DataFrame({
    'sales': [100, 150, 130, 90]
}, index=products_first_semester)

products_second_semester = ['B', 'C', 'E', 'F']
sales_second_semester = pd.DataFrame({
    'sales': [110, 170, 120, 80]
}, index=products_second_semester)
```

1. Reindexa ambos DataFrames para que contengan todos los productos de ambos semestres.
2. Rellena los valores faltantes con la media de ventas del producto correspondiente (si un producto está presente en un semestre pero no en el otro, utiliza el valor del semestre presente).
3. Combina las ventas de ambos semestres en un nuevo DataFrame.

In [ ]:
products_first_semester = ['A', 'B', 'C', 'D']
sales_first_semester = pd.DataFrame({
    'sales': [100, 150, 130, 90]
}, index=products_first_semester)

products_second_semester = ['B', 'C', 'E', 'F']
sales_second_semester = pd.DataFrame({
    'sales': [110, 170, 120, 80]
}, index=products_second_semester)

indices = sales_first_semester.index.union(sales_second_semester.index)

df1= sales_first_semester.reindex(indices)
df2= sales_second_semester.reindex(indices)


df1=df1.fillna(df1.mean())
df2=df2.fillna(df2.mean())
df3=pd.concat([df1, df2], axis=1)

display(df3)

   sales  sales
A  100.0  120.0
B  150.0  110.0
C  130.0  170.0
D   90.0  120.0
E  117.5  120.0
F  117.5   80.0

### <font color='green'>Actividad 1</font>

En una universidad internacional, se han registrado las calificaciones de los estudiantes en distintas materias y semestres. Estas calificaciones están almacenadas en un DataFrame con multiíndices, donde el primer nivel es el país de origen del estudiante y el segundo nivel es su número de identificación. Quieres analizar las calificaciones según diferentes criterios.

```
# Creando un índice multinivel
countries = ['USA', 'UK', 'Chile', 'Germany']
student_ids = [101, 102, 103, 104, 105, 106, 107, 108]
multi_index = pd.MultiIndex.from_product([countries, student_ids[:2]], names=['Country', 'Student ID'])

# Data
data = {
    'Math': np.random.randint(60, 100, len(multi_index)),
    'Physics': np.random.randint(60, 100, len(multi_index)),
    'History': np.random.randint(60, 100, len(multi_index))
}

df = pd.DataFrame(data, index=multi_index)
```

1. Selecciona las calificaciones de todos los estudiantes de Chile.
2. Obtener el promedio de calificaciones en Matemáticas para cada país.
3. Filtra los estudiantes que obtuvieron más de 90 en Historia.
4. Encuentra el estudiante con la calificación más alta en Física de cada país.
5. Cambia el nivel de los índices, haciendo que 'Student ID' sea el nivel principal y 'Country' el segundo nivel.

In [65]:
# Creando un índice multinivel
countries = ['USA', 'UK', 'Chile', 'Germany']
student_ids = [101, 102, 103, 104, 105, 106, 107, 108]
multi_index = pd.MultiIndex.from_product([countries, student_ids[:2]], names=['Country', 'Student ID'])

# Data
data = {
    'Math': np.random.randint(60, 100, len(multi_index)),
    'Physics': np.random.randint(60, 100, len(multi_index)),
    'History': np.random.randint(60, 100, len(multi_index))
}

df = pd.DataFrame(data, index=multi_index)

df.loc["Chile"]

prom_usa= df.loc[("USA", "Math")].mean()
prom_uk= df.loc[("UK", "Math")].mean()
prom_chl= df.loc[("Chile", "Math")].mean()
prom_germ= df.loc[("Germany", "Math")].mean()

mayor_90= df[df["History"]>90]

max_usa= df.loc[("USA", "Physics")].max()
max_uk= df.loc[("UK", "Physics")].max()
max_chl= df.loc[("Chile", "Physics")].max()
max_germ= df.loc[("Germany", "Physics")].max()

df= df.swaplevel("Country", "Student ID")

display(df)

                    Math  Physics  History
Student ID Country
101        USA        65       95       97
102        USA        99       94       94
101        UK         66       62       88
102        UK         62       72       69
101        Chile      98       81       82
102        Chile      81       87       64
101        Germany    84       94       70
102        Germany    79       64       65

### <font color='green'>Actividad 1</font>

La biblioteca de una universidad ha registrado un conjunto de libros de diferentes géneros, autores y años de publicación. Se te pide analizar y clasificar este conjunto de libros utilizando diferentes criterios de ordenación en un DataFrame. Algunos de estos libros han sido prestados a estudiantes y tienen fechas de devolución.

```
# Creación del DataFrame
data = {
    'Titulo': ['Programming in Python', 'History of World War II', 'Data Structures', 'Philosophy 101', 'Advanced Calculus', 'Literature of the 20th Century', 'Physics Fundamentals', 'Chemistry Basics', 'The Art of Writing', 'Biology Concepts'],
    'Autor': ['John Smith', 'Jane Doe', 'Alan Turing', 'Sophia Loren', 'Leonhard Euler', 'Oscar Wilde', 'Richard Feynman', 'Marie Curie', 'George Orwell', 'Charles Darwin'],
    'Genero': ['Programming', 'History', 'Computer Science', 'Philosophy', 'Mathematics', 'Literature', 'Physics', 'Chemistry', 'Literature', 'Biology'],
    'Año de publicación': [2020, 2005, 1995, 2010, 2000, 1985, 1990, 1998, 2002, 1880],
    'Fecha de devolución': [np.nan, '2023-05-21', '2023-05-22', np.nan, '2023-05-15', np.nan, '2023-05-18', np.nan, '2023-05-25', '2023-05-14']
}

df = pd.DataFrame(data)
df['Fecha de devolución'] = pd.to_datetime(df['Fecha de devolución'])
```

1. Ordena el DataFrame por 'Genero' y, dentro de cada género, por 'Año de publicación' en orden descendente.
2. Crea una serie que represente la cantidad de libros por género y ordena esta serie de manera descendente.
3. Ordena el DataFrame por 'Fecha de devolución', colocando primero los libros que aún no han sido devueltos (es decir, los valores NaN).
4. Para aquellos libros que han sido prestados y devueltos, ordena primero por la cercanía de la fecha de devolución y, en caso de empate, por el título del libro en orden alfabético.
5. Crea una columna que represente el año actual menos el 'Año de publicación' (esto dará la edad del libro) y ordena el DataFrame por esta nueva columna en orden ascendente.

In [ ]:
# Creación del DataFrame
data = {
    'Titulo': ['Programming in Python', 'History of World War II', 'Data Structures', 'Philosophy 101', 'Advanced Calculus', 'Literature of the 20th Century', 'Physics Fundamentals', 'Chemistry Basics', 'The Art of Writing', 'Biology Concepts'],
    'Autor': ['John Smith', 'Jane Doe', 'Alan Turing', 'Sophia Loren', 'Leonhard Euler', 'Oscar Wilde', 'Richard Feynman', 'Marie Curie', 'George Orwell', 'Charles Darwin'],
    'Genero': ['Programming', 'History', 'Computer Science', 'Philosophy', 'Mathematics', 'Literature', 'Physics', 'Chemistry', 'Literature', 'Biology'],
    'Año de publicación': [2020, 2005, 1995, 2010, 2000, 1985, 1990, 1998, 2002, 1880],
    'Fecha de devolución': [np.nan, '2023-05-21', '2023-05-22', np.nan, '2023-05-15', np.nan, '2023-05-18', np.nan, '2023-05-25', '2023-05-14']
}

df = pd.DataFrame(data)
df['Fecha de devolución'] = pd.to_datetime(df['Fecha de devolución'])

d = {}

for i in df["Genero"]:
    if i in d:
        d[i] += 1  
    else:
        d[i] = 1  

serie= pd.Series(d)
serie= serie.sort_values(ascending=  False)

df=df["Fecha de devolución"].sort_values(ascending=True, na_position="first")


df

0          NaT
3          NaT
5          NaT
7          NaT
9   2023-05-14
4   2023-05-15
6   2023-05-18
1   2023-05-21
2   2023-05-22
8   2023-05-25
Name: Fecha de devolución, dtype: datetime64[ns]

### <font color='green'>Actividad 1</font>

Se tiene un conjunto de restaurantes en ciudades de Chile, en las que se tiene cada ciudad y el tipo de cocina en cada una.



```
data_restaurantes = {
    'ciudades': ['Valparaíso','Valparaíso','Valparaíso','Valparaíso','Valparaíso','Valparaíso','Santiago','Santiago','Santiago','Santiago','Santiago','Punta Arenas','Punta Arenas','Punta Arenas'],
    'culinaria': ['Chorrillana','Chorrillana','Charquicán','Pulmay','Tallarines','Chorrillana','Tallarines','Charquicán','Porotos','Chorrillana','Porotos','Porotos','Tallarines','Charquicán']
}

restaurantes_dataframe_pares = pd.DataFrame(data_restaurantes)
restaurantes_dataframe_pares
```

1. Generar una tabla que permita contar la presencia de cada tipo de cocina en cada ciudad.
2. Genera una tabla sólo para la ciudad de Valparaíso.

In [113]:
data_restaurantes = {
    'ciudades': ['Valparaíso','Valparaíso','Valparaíso','Valparaíso','Valparaíso','Valparaíso','Santiago','Santiago','Santiago','Santiago','Santiago','Punta Arenas','Punta Arenas','Punta Arenas'],
    'culinaria': ['Chorrillana','Chorrillana','Charquicán','Pulmay','Tallarines','Chorrillana','Tallarines','Charquicán','Porotos','Chorrillana','Porotos','Porotos','Tallarines','Charquicán']
}

restaurantes_dataframe_pares = pd.DataFrame(data_restaurantes)

df= restaurantes_dataframe_pares.groupby(by= "ciudades").count()

df2= df.drop(index=["Santiago", "Punta Arenas"])

display(df)
display(df2)

              culinaria
ciudades
Punta Arenas          3
Santiago              5
Valparaíso            6

            culinaria
ciudades
Valparaíso          6

### <font color='green'>Actividad 2</font>

Eres el analista de datos de una cadena de tiendas que vende diferentes tipos de productos electrónicos. Tienes un conjunto de datos que contiene información sobre las ventas de diferentes productos en varias sucursales de la cadena durante un mes determinado. Tu tarea es analizar y resumir esta información para identificar patrones y tendencias.

Genera un DataFrame simulado con los siguientes datos:

```
import pandas as pd
import numpy as np

np.random.seed(0)

sucursales = ['Centro', 'Norte', 'Sur', 'Este', 'Oeste']
productos = ['Smartphone', 'Laptop', 'Audífonos', 'Cargador', 'Tablet']

data = {
    'Sucursal': np.random.choice(sucursales, 500),
    'Producto': np.random.choice(productos, 500),
    'Ventas (unidades)': np.random.randint(1, 50, 500),
    'Ingreso ($)': np.random.randint(10, 1000, 500)
}

df = pd.DataFrame(data)
```

1. Agrupa el DataFrame por 'Sucursal' y calcula el ingreso total por sucursal.
2. Determina cuál es el producto más vendido en términos de unidades para cada sucursal.
3. Calcula el precio promedio de venta (Ingreso $ / Ventas unidades) para cada producto.
4. Agrupa por 'Producto' y 'Sucursal' y calcula el total de unidades vendidas. 5. ¿Hay algún producto que se venda particularmente bien o mal en alguna sucursal específica?
6. Encuentra la sucursal que tiene el mayor número de ventas (unidades) y el producto más vendido en esa sucursal.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

sucursales = ['Centro', 'Norte', 'Sur', 'Este', 'Oeste']
productos = ['Smartphone', 'Laptop', 'Audífonos', 'Cargador', 'Tablet']

data = {
    'Sucursal': np.random.choice(sucursales, 500),
    'Producto': np.random.choice(productos, 500),
    'Ventas (unidades)': np.random.randint(1, 50, 500),
    'Ingreso ($)': np.random.randint(10, 1000, 500)
}

df = pd.DataFrame(data)

df1= df.groupby(by="Sucursal").sum()
df1_1= df1.drop(["Producto", "Ventas (unidades)"],axis=1)

df2= df.groupby(by=["Sucursal", "Producto"]).sum()
df2= df2.drop(["Ingreso ($)"],axis=1)
df2_1= df2.groupby(by="Sucursal")["Ventas (unidades)"].max()

display(df1)

x= df1["Sucursal"]
y= df1["Ingreso ($)"]

plt.bar(x,y)
display(df1_1)
display(df2)

grupo= df.groupby("Producto").sum()

grupo["Promedio"]=  grupo["Ingreso ($)"]/grupo["Ventas (unidades)"]
display(grupo["Promedio"])

suma= df2.sum()
display(suma)

ventas_por_sucursal = df.groupby('Sucursal')['Ventas (unidades)'].sum()

sucursal_max_ventas = ventas_por_sucursal.idxmax()
print(f"Sucursal con mayor número de ventas: {sucursal_max_ventas}")

ventas_sucursal = df[df['Sucursal'] == sucursal_max_ventas]
ventas_por_producto = ventas_sucursal.groupby('Producto')['Ventas (unidades)'].sum()

producto_max_ventas = ventas_por_producto.idxmax()
print(f"Producto más vendido en {sucursal_max_ventas}: {producto_max_ventas}")

,Producto,Ventas (unidades),Ingreso ($)
Sucursal,,,
Centro,AudífonosLaptopTabletAudífonosAudífonosSmartph...,2395,49948
Este,AudífonosTabletCargadorAudífonosCargadorSmartp...,3173,58183
Norte,TabletSmartphoneSmartphoneCargadorSmartphoneCa...,2580,51949
Oeste,LaptopAudífonosSmartphoneAudífonosTabletCargad...,2292,42971
Sur,TabletLaptopSmartphoneTabletTabletLaptopTablet...,2345,43414

KeyError: 'Sucursal'

:

Trabajas como analista de datos en una plataforma de cursos en línea. Se te ha proporcionado un conjunto de datos que contiene la actividad de los usuarios en diferentes cursos. Los datos incluyen el día, el curso en el que estaban activos, la duración de la actividad y el tipo de actividad (por ejemplo, "Ver Video", "Participar en Foro", "Realizar Examen").

Tu tarea es utilizar tablas dinámicas para analizar y resumir esta actividad y obtener insights sobre el comportamiento de los usuarios.

Genera un DataFrame simulado con los siguientes datos:

```
import pandas as pd
import numpy as np

np.random.seed(123)

dias = pd.date_range(start="2022-01-01", end="2022-01-31", freq='D')
cursos = ['Python Básico', 'Data Science Avanzado', 'Machine Learning', 'Web Development', 'Diseño Gráfico']
actividades = ['Ver Video', 'Participar en Foro', 'Realizar Examen']

data = {
    'Fecha': np.random.choice(dias, 1000),
    'Curso': np.random.choice(cursos, 1000),
    'Actividad': np.random.choice(actividades, 1000),
    'Duración (min)': np.random.randint(5, 120, 1000)
}

df = pd.DataFrame(data)
```

1. Crea una tabla dinámica que muestre el tiempo total (suma de la duración) que los usuarios pasaron en cada actividad, desglosado por curso.
2. Muestra el promedio de tiempo que los usuarios pasan en las actividades, pero esta vez desglosado por día del mes.
3. Encuentra qué curso tiene la mayor participación en foros en promedio durante los fines de semana (sábados y domingos).
4. ¿Cuál es la actividad principal (en términos de tiempo total) para cada curso?

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(123)

dias = pd.date_range(start="2022-01-01", end="2022-01-31", freq='D')
dias=pd.to_datetime(dias)
cursos = ['Python Básico', 'Data Science Avanzado', 'Machine Learning', 'Web Development', 'Diseño Gráfico']
actividades = ['Ver Video', 'Participar en Foro', 'Realizar Examen']

data = {
    'Fecha': np.random.choice(dias, 1000),
    'Curso': np.random.choice(cursos, 1000),
    'Actividad': np.random.choice(actividades, 1000),
    'Duración (min)': np.random.randint(5, 120, 1000)
}

df = pd.DataFrame(data)

df2=df.pivot_table(index="Curso", columns="Actividad",values="Duración (min)")
display(df2)

df3=df.pivot_table(index="Fecha",columns="Actividad",values="Duración (min)")
display(df3)

df4=df.pivot_table(index="Curso",columns="Fecha",values="Duración (min)")
display(df4)

fechas= ["2022-01-01", "2022-01-02", "2022-01-08","2022-01-09", "2022-01-15","2022-01-16","2022-01-22","2022-01-23", "2022-01-29", "2022-01-30"]
df5= df4[fechas]

promedio_data=df5.loc["Data Science Avanzado"].mean()
promedio_dg=df5.loc["Diseño Gráfico"].mean()
promedio_ml=df5.loc["Machine Learning"].mean()
promedio_py=df5.loc["Python Básico"].mean()
promedio_web=df5.loc["Web Development"].mean()

display(promedio_data,promedio_dg,promedio_ml,promedio_py,promedio_web)

Actividad              Participar en Foro  Realizar Examen  Ver Video
Curso
Data Science Avanzado           64.065574        69.361111  62.072727
Diseño Gráfico                  59.000000        64.939394  60.402778
Machine Learning                63.796875        61.400000  55.608696
Python Básico                   59.661538        60.306452  68.681159
Web Development                 65.867647        54.493151  60.102941

Actividad   Participar en Foro  Realizar Examen  Ver Video
Fecha
2022-01-01          107.000000        56.055556  64.928571
2022-01-02           66.000000        66.272727  58.666667
2022-01-03           44.250000        50.500000  50.142857
2022-01-04           68.333333        50.454545  61.062500
2022-01-05           66.500000        67.333333  58.272727
2022-01-06           65.933333        49.625000  58.750000
2022-01-07           64.181818        72.071429  62.444444
2022-01-08           63.777778        66.913043  60.500000
2022-01-09           77.909091        66.125000  69.400000
2022-01-10           60.555556        48.785714  72.000000
2022-01-11           76.750000        67.000000  55.142857
2022-01-12           67.250000        63.000000  54.428571
2022-01-13           53.916667        50.833333  51.000000
2022-01-14           66.153846        53.230769  65.555556
2022-01-15           44.600000        68.105263  65.461538
2022-01-16           51.428571        76.846154  64.545455
2022-01-17           66.400000        78.666667  51.307692
2022-01-18           65.750000        65.300000  67.375000
2022-01-19           77.166667        63.333333  67.000000
2022-01-20           56.625000        59.117647  55.545455
2022-01-21           69.900000        53.833333  49.642857
2022-01-22           63.625000        75.375000  60.615385
2022-01-23           57.384615        72.000000  74.100000
2022-01-24           52.000000        48.692308  56.142857
2022-01-25           66.100000        36.300000  64.142857
2022-01-26           67.700000        44.400000  73.769231
2022-01-27           52.062500        62.909091  56.714286
2022-01-28           53.083333        69.769231  60.181818
2022-01-29           68.900000        67.545455  78.833333
2022-01-30           76.000000        78.181818  52.111111
2022-01-31           56.950000        72.000000  68.250000

Fecha,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,...,2022-01-22,2022-01-23,2022-01-24,2022-01-25,2022-01-26,2022-01-27,2022-01-28,2022-01-29,2022-01-30,2022-01-31
Curso,,,,,,,,,,,,,,,,,,,,,
Data Science Avanzado,73.750,56.900000,38.750000,56.666667,19.50,64.000000,56.166667,68.272727,70.833333,45.000000,...,56.428571,71.0,67.875000,107.000000,114.000000,42.333333,72.428571,68.200000,77.166667,74.923077
Diseño Gráfico,66.000,77.500000,46.333333,57.428571,63.25,29.500000,66.666667,79.714286,54.500000,65.833333,...,57.000000,68.5,36.166667,60.666667,61.000000,75.714286,55.625000,59.600000,57.000000,53.500000
Machine Learning,58.875,79.571429,51.250000,73.333333,85.50,45.400000,50.600000,48.642857,78.666667,58.666667,...,75.333333,70.5,59.750000,53.666667,54.800000,54.571429,54.250000,70.428571,86.888889,41.714286
Python Básico,63.000,85.800000,38.666667,55.727273,57.00,75.090909,76.000000,62.000000,66.285714,61.666667,...,84.500000,61.5,35.500000,47.428571,45.250000,71.222222,60.714286,86.000000,47.333333,69.181818
Web Development,58.900,35.714286,56.818182,53.666667,65.80,59.000000,75.285714,74.375000,81.888889,48.600000,...,63.200000,31.0,60.166667,36.875000,74.111111,30.250000,61.200000,68.600000,69.142857,61.600000

np.float64(69.23301448551447)

np.float64(65.48597402597403)

np.float64(69.04623015873015)

np.float64(68.21857142857144)

np.float64(57.687103174603166)